# Generated by Django 3.2 on 2021-10-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin', models.CharField(max_length=100)),
                ('via', models.CharField(max_length=500)),
                ('etc', models.CharField(max_length=500)),
            ],
        ),
    ]
